name: Build and Deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      uses: docker/build-push-action@v1
      with:
        context: ../../.
        dockerfile: Dockerfile
        tags: latest-${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Docker image
      uses: docker/deploy-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: my-repository
        tags: latest-${{ github.sha }}
